services:
  mysql-db:
    image: mysql:9.7.2
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
