# Conversion to YAML from Properties formar report
# Warnings:
# - Multiple values [java.io.IOException, org.springframework.web.client.ResourceAccessException, com.example.demo.exception.BusinessException] assigned to '-'. Values are merged into a yaml sequence node.
spring:
  application:
    name: resilence4j

  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: secret
    hikari:
      maximum-pool-size: 50
      minimum-idle: 30
      
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      auto-commit: true
      pool-name: prkwanHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: logs/resilience4j.log
  
  level:
    "[org.zalando.logbook]": TRACE
  structured:
    format:
      console: ecs

logbook:
  predicate:
    include:
      - path: "/**"

  obfuscate:
    headers:
      - authorization            # Mask Authorization header
      - Cookie                   # Mask Cookie header
      - testheader
    parameters:
      - password                 # Mask query/form parameters
      - token                    # Mask token parameters
    json-body-fields:
      - password
      - secret
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,ratelimiters,retries,bulkheads
  endpoint:
    health:
      show-details: always
resilience4j:
  retry:
    metrics:
      legacy:
        enabled: true
    configs:
      default:
        max-attempts: 3             # 1 initial call + 2 retries
        wait-duration: 500ms        # wait between attempts
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        # retry-exceptions:
        #   - java.io.IOException
        #   - org.springframework.web.client.ResourceAccessException
        #   - com.example.springboot.resilience4j.exception.DownstreamPricingException
        # ignore-exceptions:
        #   - com.example.demo.exception.BusinessException
    instances:
      priceService:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
        cancel-running-future: true
    instances:
      priceService:
        base-config: default
  circuitbreaker:
    metrics:
      legacy:
        enabled: true
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20            # number of calls to measure
        minimum-number-of-calls: 10
        failure-rate-threshold: 50         # percentage
        wait-duration-in-open-state: 30s   # how long circuit stays OPEN
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
        # ignore-exceptions:
        #   - com.example.demo.exception.BusinessException
    instances:
      priceService:
        base-config: default